# GMM (Gaussian Mixture Model)

In [1]:
import numpy as np

X = np.array([
    # Cluster-like group 1
    [1.0, 1.5],
    [1.5, 2.0],
    [2.0, 1.0],
    [2.5, 1.8],
    [1.8, 2.5],
    [2.2, 2.2],
    [1.2, 2.3],
    [2.8, 1.2],
    [1.7, 1.3],
    [2.3, 1.6],

    # Cluster-like group 2
    [7.0, 7.5],
    [7.5, 8.0],
    [8.0, 7.0],
    [8.5, 7.8],
    [7.8, 8.5],
    [8.2, 8.2],
    [7.2, 8.3],
    [8.8, 7.2],
    [7.7, 7.3],
    [8.3, 7.6],

    # Cluster-like group 3
    [1.0, 8.0],
    [1.5, 8.5],
    [2.0, 7.5],
    [2.5, 8.2],
    [1.8, 8.8],
    [2.2, 8.3],
    [1.2, 8.7],
    [2.8, 7.7],
    [1.7, 7.8],
    [2.3, 8.1]
])

print(X.shape)

(30, 2)


# Parameters

In [2]:
K = 3               # Number of Clusters
N, D = X.shape      # N = samples and D = Features

# Initialize Means

In [3]:
np.random.seed(42)

indices = np.random.choice(N, K, replace = False)

mu = X[indices].copy()

# Initialize Covariance Matrices

In [4]:
covariances = np.array([np.eye(D) for _ in range(K)])

covariances

array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]]])

# Initialize Mixing Coefficients

In [5]:
pi = np.ones(K) / K

pi

array([0.33333333, 0.33333333, 0.33333333])

In [6]:
# ==========================================
# 6. Print Initial Parameters
# ==========================================

print("Dataset shape:", X.shape)

print("\nInitial Means:")
print(mu)

print("\nInitial Covariances:")
print(covariances)

print("\nInitial Mixing Coefficients:")
print(pi)

print("\nSum of mixing coefficients:")
print(pi.sum())

Dataset shape: (30, 2)

Initial Means:
[[2.8 7.7]
 [8.2 8.2]
 [2.5 8.2]]

Initial Covariances:
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]]

Initial Mixing Coefficients:
[0.33333333 0.33333333 0.33333333]

Sum of mixing coefficients:
1.0
