# Hierarchical Clustering

In [17]:
import numpy as np

In [ ]:
import numpy as np


class HierarchicalClustering:

    def __init__(self):
        self.clusters = []

    # ---------------------------------------------------
    # Euclidean Distance
    # ---------------------------------------------------

    def euclidean_distance(self, x1, x2):

        return np.sqrt(np.sum((x1 - x2) ** 2))

    # ---------------------------------------------------
    # Distance Matrix
    # ---------------------------------------------------

    def build_distance_matrix(self, X):

        n = len(X)

        distance_matrix = np.zeros((n, n))

        for i in range(n):

            for j in range(i + 1, n):

                dist = self.euclidean_distance(X[i], X[j])

                distance_matrix[i][j] = dist
                distance_matrix[j][i] = dist

        return distance_matrix

    # ---------------------------------------------------
    # Find Global Minimum Distance
    # ---------------------------------------------------

    def find_min_distance(self, distance_matrix):

        temp_min = np.inf

        t_i, t_j = -1, -1

        n = len(distance_matrix)

        for i in range(n):

            for j in range(i + 1, n):

                if distance_matrix[i][j] < temp_min:

                    temp_min = distance_matrix[i][j]

                    t_i, t_j = i, j

        return t_i, t_j, temp_min

    # ---------------------------------------------------
    # Fit
    # ---------------------------------------------------

    def fit(self, X):

        X = np.array(X)

        self.clusters = [[i] for i in range(len(X))] # sampling cluster from data

        while len(X) > 1:

            # Distance Matrix
            distance_matrix = self.build_distance_matrix(X)

            print("\nDistance Matrix")
            print(distance_matrix)

            # Find Minimum Distance
            t_i, t_j, min_dist = self.find_min_distance(distance_matrix)

            print("\nMinimum Distance :", min_dist)
            
            print(
                "Merging :",
                self.clusters[t_i],
                self.clusters[t_j]
            )

            # Merge Clusters
            self.clusters[t_i] = (
                self.clusters[t_i]
                + self.clusters[t_j]
            )

            self.clusters.pop(t_j)

            # Remove merged point
            X = np.delete(X, t_j, axis=0)
            print("\n X : ", X)

            print("\nClusters :", self.clusters)

        return self.clusters


In [19]:
# ---------------------------------------------------
# Example
# ---------------------------------------------------

X = np.array([
    [1],
    [2],
    [10],
    [11]
])

hc = HierarchicalClustering()

clusters = hc.fit(X)

print("\nFinal Cluster")
print(clusters)


Distance Matrix
[[ 0.  1.  9. 10.]
 [ 1.  0.  8.  9.]
 [ 9.  8.  0.  1.]
 [10.  9.  1.  0.]]

Minimum Distance : 1.0
Merging : [0] [1]

 X :  [[ 1]
 [10]
 [11]]

Clusters : [[0, 1], [2], [3]]

Distance Matrix
[[ 0.  9. 10.]
 [ 9.  0.  1.]
 [10.  1.  0.]]

Minimum Distance : 1.0
Merging : [2] [3]

 X :  [[ 1]
 [10]]

Clusters : [[0, 1], [2, 3]]

Distance Matrix
[[0. 9.]
 [9. 0.]]

Minimum Distance : 9.0
Merging : [0, 1] [2, 3]

 X :  [[1]]

Clusters : [[0, 1, 2, 3]]

Final Cluster
[[0, 1, 2, 3]]
