# Import


In [2]:
import torch

import torch.nn as nn

# Data

In [3]:
vocab = {
    "I" : 0,
    "Love" : 1,
    "AI" : 2,
    "and" : 3,
    "PyTorch" : 4
}

vocab_size = len(vocab)
vocab_size

5

# Convert sentence to tokens

In [4]:
# I Love AI  -> 012
# just a lookup table

tokens = torch.tensor([0, 1, 2])

print(tokens)
print(tokens.shape)

tensor([0, 1, 2])
torch.Size([3])


# Create Embedding Layer

In [5]:
embedding_dim = 8

# creating a obj for embedding
# text to embed Example:
# I -> [-0.6207,  0.0349,  0.0896, -1.3563, -0.9755,  1.4167, -1.8134, -2.1788]
# Why 8? cause we put embedding_dim = 8

embedding = nn.Embedding(
    num_embeddings = vocab_size,
    embedding_dim = embedding_dim
)

In [6]:
# in tokens i have only 3 (0, 1, 2)
# just accessing embedding for the first 3 tokens

# illustration
# I    -> 0 -> [-0.6207,  0.0349,  0.0896, -1.3563, -0.9755,  1.4167, -1.8134, -2.1788]
# Love -> 1 -> [ 0.0684,  0.0784, -0.8352,  1.1685,  0.6589, -0.7665, -0.6419,  0.0317]
# AI   -> 2 -> [ 0.4224,  0.7009, -0.9845, -1.1494,  1.1792,  0.7312, -0.8205, -0.2286]

x = embedding(tokens)
x

tensor([[-0.7982, -1.3787, -0.2716, -0.2680,  0.0421,  0.7754,  0.7049, -0.7194],
        [ 0.4427, -0.6754,  0.7466, -0.4202,  0.6790, -0.7893,  0.7407,  0.4108],
        [ 0.4920, -0.4324, -0.4770,  1.5163, -0.3222, -0.0613, -0.5180,  0.6448]],
       grad_fn=<EmbeddingBackward0>)

In [7]:
x.shape

torch.Size([3, 8])

# Adding Linear Layer

In [8]:
# create a obj for Linear

linear = nn.Linear(
    in_features = 8,
    out_features = 8
)

# use the x in Linear Layer

In [9]:
y = linear(x)

print("Tokens Shape:", tokens.shape)
print("Embedding Shape:", x.shape)
print("Output Shape:", y.shape)

Tokens Shape: torch.Size([3])
Embedding Shape: torch.Size([3, 8])
Output Shape: torch.Size([3, 8])


In [10]:
tokens

tensor([0, 1, 2])

In [11]:
x

tensor([[-0.7982, -1.3787, -0.2716, -0.2680,  0.0421,  0.7754,  0.7049, -0.7194],
        [ 0.4427, -0.6754,  0.7466, -0.4202,  0.6790, -0.7893,  0.7407,  0.4108],
        [ 0.4920, -0.4324, -0.4770,  1.5163, -0.3222, -0.0613, -0.5180,  0.6448]],
       grad_fn=<EmbeddingBackward0>)

In [12]:
y

tensor([[ 0.2705, -0.0623,  0.2540,  0.3906,  0.4525, -0.0409,  0.7062,  0.1534],
        [ 0.2121, -0.3601, -0.1456,  0.1911,  0.6694,  0.4388,  1.0075, -0.2088],
        [ 0.2927,  0.1227, -0.3924, -0.1136, -0.0937, -0.7598, -0.1755, -0.1488]],
       grad_fn=<AddmmBackward0>)