# 01 — PyTorch Basics

## Learning Objectives

By the end of this notebook, you should be able to:

- Understand what PyTorch is and why it is used.
- Create and inspect tensors.
- Understand tensor shape, dimensions, size, dtype, and device.
- Create tensors using different PyTorch functions.
- Index and slice tensors.
- Perform basic tensor operations.
- Understand CPU vs GPU tensors.
- Move tensors between devices.
- Understand important PyTorch parameters through experiments.
- Identify common tensor errors.

> **Teaching approach:** Don't just memorize functions. For every important parameter, we will change it, observe the output, and understand **why** the output changed.

## 1. What is PyTorch?

**PyTorch** is an open-source machine learning and deep learning framework developed primarily by Meta AI.

It provides tools for:

- Tensor computation
- Automatic differentiation
- Neural networks
- GPU acceleration
- Model training and inference
- Computer vision
- Natural language processing
- Reinforcement learning

The most fundamental object in PyTorch is the **tensor**.

### Tensor

A tensor is a generalization of:

- Scalar → 0-dimensional tensor
- Vector → 1-dimensional tensor
- Matrix → 2-dimensional tensor
- Higher-dimensional arrays → 3D, 4D, 5D, ...

A neural network ultimately performs mathematical operations on tensors.

In [1]:
import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.9.1


## 2. Why PyTorch instead of normal Python lists or NumPy?

Python lists are excellent for general programming, and NumPy is excellent for numerical computing.

PyTorch adds several features important for deep learning:

| Feature | Python List | NumPy | PyTorch |
|---|---:|---:|---:|
| Numerical operations | Limited | ✅ | ✅ |
| Multidimensional arrays | Limited | ✅ | ✅ |
| GPU acceleration | ❌ | Usually ❌ | ✅ |
| Automatic gradients | ❌ | ❌ | ✅ |
| Deep-learning ecosystem | ❌ | ❌ | ✅ |

PyTorch tensors are conceptually similar to NumPy arrays, but PyTorch is designed to work naturally with neural-network training and accelerators such as GPUs.

# 3. Creating Tensors

There are several common ways to create tensors.

We will study:

1. `torch.tensor()`
2. `torch.zeros()`
3. `torch.ones()`
4. `torch.full()`
5. `torch.empty()`
6. `torch.arange()`
7. `torch.linspace()`
8. `torch.rand()`
9. `torch.randn()`
10. `torch.randint()`

## 3.1 `torch.tensor()`

### Definition

`torch.tensor()` creates a tensor from existing data.

### Basic syntax

```python
torch.tensor(data, dtype=None, device=None, requires_grad=False)
```

### Important parameters

- `data` → the input values.
- `dtype` → numerical data type.
- `device` → CPU or GPU.
- `requires_grad` → whether PyTorch should track operations for gradients.

The most necessary parameter is **`data`**. The others are optional for simple tensor creation.

In [2]:
x = torch.tensor([1, 2, 3, 4])

print(x)
print("Type:", type(x))

tensor([1, 2, 3, 4])
Type: <class 'torch.Tensor'>


## 3.2 Tensor from nested lists

Nested lists create multidimensional tensors.

In [4]:
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

tensor([[1, 2, 3],
        [4, 5, 6]])


Here:

- Number of rows = `2`
- Number of columns = `3`
- Shape = `(2, 3)`
- Dimensions = `2`

This distinction between **shape** and **number of dimensions** is extremely important in deep learning.

# 4. Tensor Shape and Dimensions

A tensor has several useful properties in other words we say attribute (which is simply a varible) and methods (simply functions)

- `shape`
- `size()`
- `ndim`
- `numel()`
- `dtype`
- `device`

In [ ]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("Tensor:")
print(x)

print("\nShape:", x.shape) # x.shape is just an alias for x.size()
print("Size:", x.size())
print("Dimensions:", x.ndim) # Dimensions
print("Number of elements:", x.numel()) # number of element in short numel
print("Data type:", x.dtype) # data type
print("Device:", x.device) # GPU or CPU

Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Shape: torch.Size([2, 3])
Size: torch.Size([2, 3])
Dimensions: 2
Number of elements: 6
Data type: torch.int64
Device: cpu


### Understanding the output

For a `(2, 3)` tensor:

```text
2 × 3 = 6 elements
```

So:

```python
x.shape   # torch.Size([2, 3])
x.ndim    # 2
x.numel() # 6
```

### Important idea

**Shape tells you the size of every dimension.**

For example:

```text
(3,)        → vector
(2, 3)      → matrix
(2, 3, 4)   → 3-dimensional tensor
(32, 3, 224, 224) → batch of RGB images
```

# 5. Data Types (`dtype`)

PyTorch supports many numerical data types.

Common ones include:

- `torch.float32`
- `torch.float64`
- `torch.float16`
- `torch.bfloat16`
- `torch.int8`
- `torch.int16`
- `torch.int32`
- `torch.int64`
- `torch.bool`

For many neural-network operations, **`float32`** is the standard starting point.

Class labels are commonly stored as **`int64` (`torch.long`)**, especially when using `CrossEntropyLoss`.

In [6]:
x = torch.tensor([1, 2, 3])

print(x)
print(x.dtype)

y = torch.tensor([1.0, 2.0, 3.0])

print(y)
print(y.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


## 5.1 Explicitly specifying `dtype`

The `dtype` parameter controls how values are represented in memory and how numerical operations are performed.

In [7]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.float64)

print("x:", x)
print("x dtype:", x.dtype)

print("\ny:", y)
print("y dtype:", y.dtype)

x: tensor([1., 2., 3.])
x dtype: torch.float32

y: tensor([1., 2., 3.], dtype=torch.float64)
y dtype: torch.float64


### Why does `dtype` matter?

Changing dtype can affect:

- Memory usage
- Numerical precision
- Speed
- GPU compatibility
- Training performance

For example, `float64` generally uses more memory than `float32`.

Do not assume that "higher precision" automatically means "better" for deep learning. The appropriate dtype depends on the operation and hardware.

# 6. Creating Special Tensors

## `torch.zeros()`

Creates a tensor filled with zeros.

```python
torch.zeros(size, dtype=None, device=None, requires_grad=False)
```

The **size/shape** is the necessary input.

In [8]:
x = torch.zeros(2, 3)

print(x)
print("Shape:", x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape: torch.Size([2, 3])


### What happens if we change the dimensions?

In [9]:
x = torch.zeros(4, 2)

print(x)
print("Shape:", x.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
Shape: torch.Size([4, 2])


The output changed because we changed the requested shape:

```text
torch.zeros(2, 3) → 2 rows × 3 columns
torch.zeros(4, 2) → 4 rows × 2 columns
```

## `torch.ones()`

Creates a tensor filled with ones.

```python
torch.ones(size, dtype=None, device=None, requires_grad=False)
```

In [10]:
x = torch.ones(3, 4)

print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## `torch.full()`

Creates a tensor filled with a specified value.

```python
torch.full(size, fill_value, dtype=None, device=None, requires_grad=False)
```

Two important inputs are:

- `size` → tensor shape
- `fill_value` → value used for every element

In [11]:
x = torch.full((2, 3), fill_value=7)

print(x)

tensor([[7, 7, 7],
        [7, 7, 7]])


### Change `fill_value`

In [12]:
x = torch.full((2, 3), fill_value=100)

print(x)

tensor([[100, 100, 100],
        [100, 100, 100]])


Only the stored value changed because the **shape remained `(2, 3)`** while `fill_value` changed from `7` to `100`.

# 7. `torch.empty()`

`torch.empty()` creates a tensor without initializing its values.

```python
torch.empty(size, dtype=None, device=None, requires_grad=False)
```

**Important:** the values are not guaranteed to be zero.

The memory contains whatever values happened to exist in that memory location.

Therefore, use `torch.zeros()` when you specifically need zeros.

In [13]:
x = torch.empty(2, 3)

print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


The values printed by `torch.empty()` should **not** be interpreted as meaningful data.

This function is useful when you plan to fill the tensor immediately and want to avoid the extra initialization step.

# 8. Creating Sequences

## `torch.arange()`

Creates values with a regular step.

```python
torch.arange(start=0, end, step=1, ...)
```

Important parameters:

- `start`
- `end`
- `step`

The `end` value is generally **exclusive**, similar to Python's `range()`.

In [14]:
x = torch.arange(0, 10, 1)

print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Change the step

In [15]:
x = torch.arange(0, 10, 2)

print(x)

tensor([0, 2, 4, 6, 8])


The output changes because `step=2` tells PyTorch to increase each value by 2:

```text
0, 2, 4, 6, 8
```

## `torch.linspace()`

Creates a specified number of evenly spaced values between two endpoints.

```python
torch.linspace(start, end, steps)
```

Unlike `arange()`, you specify the **number of values** using `steps`.

In [16]:
x = torch.linspace(0, 1, steps=5)

print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


### Change `steps`

In [17]:
x = torch.linspace(0, 1, steps=11)

print(x)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


Here the interval remains `0 → 1`, but the number of points changes.

This is useful when you want a fixed number of evenly spaced samples.

# 9. Random Tensors

Random tensors are heavily used when initializing neural-network parameters.

Common functions:

- `torch.rand()` → uniform distribution from approximately `[0, 1)`
- `torch.randn()` → standard normal distribution
- `torch.randint()` → random integers

## `torch.rand()`

```python
torch.rand(size, ...)
```

The size is the necessary input.

In [18]:
x = torch.rand(2, 3)

print(x)

tensor([[0.3540, 0.0967, 0.5387],
        [0.1007, 0.3288, 0.3219]])


Every time you execute the cell, the values normally change because they are randomly generated.

In [19]:
x = torch.rand(2, 3)

print(x)

tensor([[0.5853, 0.2711, 0.0040],
        [0.3752, 0.7161, 0.6873]])


## `torch.randn()`

`randn()` samples from a standard normal distribution with approximately:

```text
mean = 0
standard deviation = 1
```

In [20]:
x = torch.randn(2, 3)

print(x)

tensor([[-0.6040,  2.1243, -1.9560],
        [ 0.2090,  0.1770, -0.3444]])


### `rand()` vs `randn()`

```text
rand()  → uniform random values
randn() → normally distributed random values
```

The shape parameter controls the number of generated values, while the underlying function controls their distribution.

## `torch.randint()`

Creates random integer values.

```python
torch.randint(low, high, size)
```

Important parameters:

- `low` → minimum inclusive value
- `high` → maximum exclusive value
- `size` → output shape

In [21]:
x = torch.randint(0, 10, (2, 5))

print(x)

tensor([[2, 9, 7, 8, 3],
        [0, 1, 4, 7, 8]])


The generated values can be:

```text
0, 1, 2, ..., 9
```

but not `10`, because `high=10` is exclusive.

# 10. Indexing

PyTorch indexing is similar to NumPy and Python.

In [22]:
x = torch.tensor([10, 20, 30, 40, 50])

print("First element:", x[0])
print("Third element:", x[2])
print("Last element:", x[-1])

First element: tensor(10)
Third element: tensor(30)
Last element: tensor(50)


## Indexing a matrix

In [23]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("First row:", x[0])
print("Second row:", x[1])
print("Element at row 2, column 3:", x[1, 2])

First row: tensor([10, 20, 30])
Second row: tensor([40, 50, 60])
Element at row 2, column 3: tensor(60)


Remember: Python uses **zero-based indexing**.

Therefore:

```text
x[0, 0] → first row, first column
x[1, 2] → second row, third column
```

# 11. Slicing

You can select ranges of tensor elements.

```python
tensor[start:end]
```

The `end` index is exclusive.

In [24]:
x = torch.tensor([10, 20, 30, 40, 50])

print(x[1:4])
print(x[:3])
print(x[2:])
print(x[::2])

tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([30, 40, 50])
tensor([10, 30, 50])


### Understanding:

```text
x[1:4]  → indices 1, 2, 3
x[:3]   → indices 0, 1, 2
x[2:]   → index 2 onward
x[::2]  → every second element
```

# 12. Basic Tensor Arithmetic

PyTorch supports element-wise arithmetic.

Operations include:

- Addition `+`
- Subtraction `-`
- Multiplication `*`
- Division `/`
- Power `**`

In [25]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([10., 20., 30.])

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Power:", a ** 2)

Addition: tensor([11., 22., 33.])
Subtraction: tensor([ 9., 18., 27.])
Multiplication: tensor([10., 40., 90.])
Division: tensor([10., 10., 10.])
Power: tensor([1., 4., 9.])


## Important: `*` vs matrix multiplication

In PyTorch:

```python
a * b
```

means **element-wise multiplication**.

For matrix multiplication:

```python
a @ b
```

or:

```python
torch.matmul(a, b)
```

This distinction becomes critical when building neural networks.

In [26]:
a = torch.tensor([
    [1., 2.],
    [3., 4.]
])

b = torch.tensor([
    [5., 6.],
    [7., 8.]
])

print("Element-wise multiplication:")
print(a * b)

print("\nMatrix multiplication:")
print(a @ b)

Element-wise multiplication:
tensor([[ 5., 12.],
        [21., 32.]])

Matrix multiplication:
tensor([[19., 22.],
        [43., 50.]])


The outputs differ because the operations perform different mathematics.

### Element-wise multiplication

```text
[1×5, 2×6]
[3×7, 4×8]
```

### Matrix multiplication

Each output element is calculated using a row-column dot product.

# 13. Reduction Operations

Reduction operations summarize tensor values.

Important examples:

- `sum()`
- `mean()`
- `min()`
- `max()`
- `std()`

In [27]:
x = torch.tensor([1., 2., 3., 4., 5.])

print("Sum:", x.sum())
print("Mean:", x.mean())
print("Minimum:", x.min())
print("Maximum:", x.max())
print("Standard deviation:", x.std())

Sum: tensor(15.)
Mean: tensor(3.)
Minimum: tensor(1.)
Maximum: tensor(5.)
Standard deviation: tensor(1.5811)


## Reduction along a dimension

For a matrix, you can specify `dim`.

```python
x.sum(dim=0)
x.sum(dim=1)
```

This is extremely important when working with batches.

In [28]:
x = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
])

print("Tensor:")
print(x)

print("\nSum along dim=0:")
print(x.sum(dim=0))

print("\nSum along dim=1:")
print(x.sum(dim=1))

Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum along dim=0:
tensor([5., 7., 9.])

Sum along dim=1:
tensor([ 6., 15.])


For shape `(2, 3)`:

- `dim=0` reduces the rows → one value per column.
- `dim=1` reduces the columns → one value per row.

Understanding dimensions is one of the most important skills in PyTorch.

# 14. Reshaping Tensors

Common operations:

- `reshape()`
- `view()`
- `flatten()`
- `squeeze()`
- `unsqueeze()`

## `reshape()`

Changes the shape while preserving the number of elements.

```python
x.reshape(new_shape)
```

The new shape must contain the same total number of elements.

In [29]:
x = torch.arange(1, 7)

print("Original:")
print(x)
print("Shape:", x.shape)

y = x.reshape(2, 3)

print("\nReshaped:")
print(y)
print("Shape:", y.shape)

Original:
tensor([1, 2, 3, 4, 5, 6])
Shape: torch.Size([6])

Reshaped:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


The original tensor has:

```text
6 elements
```

The new shape also contains:

```text
2 × 3 = 6 elements
```

So the reshape is valid.

Try changing `(2, 3)` to `(3, 2)`.

In [30]:
x = torch.arange(1, 7)
y = x.reshape(3, 2)

print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Invalid reshape

Try this:

```python
x.reshape(4, 2)
```

It should fail because:

```text
original elements = 6
requested elements = 4 × 2 = 8
```

The number of elements cannot change during reshape.

In [31]:
x = torch.arange(1, 7)

try:
    y = x.reshape(4, 2)
except RuntimeError as e:
    print("Expected error:")
    print(e)

Expected error:
shape '[4, 2]' is invalid for input of size 6


# 15. `flatten()`

`flatten()` converts multiple dimensions into a single dimension.

This is commonly used before feeding image features into a fully connected layer.

In [32]:
x = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original shape:", x.shape)

y = x.flatten()

print("Flattened:", y)
print("Flattened shape:", y.shape)

Original shape: torch.Size([2, 2, 2])
Flattened: tensor([1, 2, 3, 4, 5, 6, 7, 8])
Flattened shape: torch.Size([8])


The tensor has shape:

```text
(2, 2, 2)
```

After flattening:

```text
(8,)
```

because:

```text
2 × 2 × 2 = 8
```

# 16. `unsqueeze()` and `squeeze()`

## `unsqueeze(dim)`

Adds a dimension of size 1.

## `squeeze(dim)`

Removes dimensions whose size is 1.

In [33]:
x = torch.tensor([1, 2, 3])

print("Original:", x.shape)

y = x.unsqueeze(0)
print("unsqueeze(0):", y.shape)

z = x.unsqueeze(1)
print("unsqueeze(1):", z.shape)

Original: torch.Size([3])
unsqueeze(0): torch.Size([1, 3])
unsqueeze(1): torch.Size([3, 1])


The position of `dim` determines **where** the new dimension is inserted.

This becomes important for image and batch dimensions.

For example, an image might have:

```text
(C, H, W)
```

and adding a batch dimension produces:

```text
(1, C, H, W)
```

In [34]:
image = torch.rand(3, 224, 224)

print("Single image:", image.shape)

batch = image.unsqueeze(0)

print("With batch dimension:", batch.shape)

Single image: torch.Size([3, 224, 224])
With batch dimension: torch.Size([1, 3, 224, 224])


# 17. Concatenation and Stacking

## `torch.cat()`

Joins tensors along an existing dimension.

## `torch.stack()`

Creates a **new dimension** and places tensors along it.

In [35]:
a = torch.tensor([1, 2])
b = torch.tensor([3, 4])

print("cat:")
print(torch.cat([a, b]))

print("\nstack:")
print(torch.stack([a, b]))

cat:
tensor([1, 2, 3, 4])

stack:
tensor([[1, 2],
        [3, 4]])


Compare their shapes:

```text
cat   → (4,)
stack → (2, 2)
```

`stack()` adds a new dimension, while `cat()` extends an existing dimension.

# 18. CPU and GPU

One of PyTorch's most important capabilities is hardware acceleration.

A tensor can live on:

```text
CPU
GPU
```

You can inspect the current device using:

```python
tensor.device
```

In [36]:
x = torch.tensor([1, 2, 3])

print("Device:", x.device)

Device: cpu


## Detecting CUDA

`torch.cuda.is_available()` tells us whether CUDA GPU support is available to PyTorch.

In [37]:
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Running with CPU only.")

CUDA available: True
GPU: NVIDIA GeForce RTX 3050 Laptop GPU


### Selecting a device

A common pattern is:

```python
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
```

This allows the same code to work on both machines with and without a CUDA-capable GPU.

In [38]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Selected device:", device)

Selected device: cuda


## Moving a tensor to the device

Use:

```python
tensor.to(device)
```

or:

```python
tensor.cuda()
```

`to(device)` is generally more flexible because it can work with either CPU or GPU.

In [39]:
x = torch.tensor([1., 2., 3.])

x = x.to(device)

print(x)
print("Device:", x.device)

tensor([1., 2., 3.], device='cuda:0')
Device: cuda:0


### Important rule

When performing operations between tensors, they generally need to be on compatible devices.

For example, a CPU tensor and CUDA tensor cannot normally be directly combined.

In [40]:
cpu_tensor = torch.tensor([1., 2., 3.])

if torch.cuda.is_available():
    gpu_tensor = torch.tensor([4., 5., 6.], device="cuda")

    try:
        print(cpu_tensor + gpu_tensor)
    except RuntimeError as e:
        print("Expected device mismatch error:")
        print(e)
else:
    print("CUDA is not available; device mismatch experiment skipped.")

Expected device mismatch error:
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


# 19. Tensor Conversion

## Tensor → NumPy

For CPU tensors, `.numpy()` can convert a tensor to a NumPy array.

In [41]:
x = torch.tensor([1, 2, 3])

numpy_array = x.numpy()

print("PyTorch tensor:", x)
print("NumPy array:", numpy_array)
print("NumPy type:", type(numpy_array))

PyTorch tensor: tensor([1, 2, 3])
NumPy array: [1 2 3]
NumPy type: <class 'numpy.ndarray'>


## NumPy → Tensor

Use:

```python
torch.from_numpy(array)
```

In [42]:
import numpy as np

array = np.array([10, 20, 30], dtype=np.float32)

tensor = torch.from_numpy(array)

print("NumPy:", array)
print("Tensor:", tensor)
print("Tensor dtype:", tensor.dtype)

NumPy: [10. 20. 30.]
Tensor: tensor([10., 20., 30.])
Tensor dtype: torch.float32


### Important

`torch.from_numpy()` can share memory with the NumPy array.

That means modifying one may affect the other.

This is different from creating a completely independent copy.

In [43]:
array = np.array([1, 2, 3], dtype=np.float32)
tensor = torch.from_numpy(array)

tensor[0] = 999

print("Tensor:", tensor)
print("NumPy array:", array)

Tensor: tensor([999.,   2.,   3.])
NumPy array: [999.   2.   3.]


# 20. Random Seeds and Reproducibility

Random initialization is common in machine learning.

If you want repeatable experiments, set a seed:

```python
torch.manual_seed(42)
```

The seed does not make values "better". It makes the random sequence reproducible.

In [44]:
torch.manual_seed(42)

a = torch.rand(5)

torch.manual_seed(42)

b = torch.rand(5)

print("a:", a)
print("b:", b)
print("Same:", torch.equal(a, b))

a: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])
b: tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])
Same: True


Try changing `42` to another number.

The generated values will change, but running the same seed again will reproduce the same sequence under the same relevant environment conditions.

# 21. `requires_grad`

This parameter is central to neural-network training.

```python
torch.tensor(
    data,
    requires_grad=True
)
```

When enabled, PyTorch tracks operations involving the tensor so that gradients can later be calculated.

We will study autograd in detail in Notebook 03. For now, understand the purpose.

In [45]:
x = torch.tensor([2.0, 3.0], requires_grad=True)

print("Tensor:", x)
print("Requires gradient:", x.requires_grad)

Tensor: tensor([2., 3.], requires_grad=True)
Requires gradient: True


# 22. Common Tensor Errors

Understanding errors is part of learning PyTorch.

### Error 1 — Invalid reshape

The number of elements must remain unchanged.

### Error 2 — Device mismatch

CPU and CUDA tensors generally cannot be directly combined.

### Error 3 — dtype mismatch

Some operations require compatible numerical types.

### Error 4 — Incorrect dimensions

Many neural-network layers expect a specific input shape.

### Error 5 — Integer tensors where floating-point tensors are expected

Neural-network computations frequently require floating-point inputs.

# 23. Practical Example — Image Tensor

Let's represent one RGB image.

A common PyTorch image layout is:

```text
(C, H, W)
```

where:

- `C` = channels
- `H` = height
- `W` = width

For an RGB image:

```text
C = 3
```

A `224 × 224` RGB image therefore has:

```text
(3, 224, 224)
```

In [46]:
image = torch.rand(3, 224, 224)

print("Image shape:", image.shape)
print("Number of dimensions:", image.ndim)
print("Number of values:", image.numel())
print("Data type:", image.dtype)
print("Device:", image.device)

Image shape: torch.Size([3, 224, 224])
Number of dimensions: 3
Number of values: 150528
Data type: torch.float32
Device: cpu


## Add a batch dimension

Neural networks commonly process multiple images at once.

For example, 32 images:

```text
(batch, channels, height, width)
```

becomes:

```text
(32, 3, 224, 224)
```

In [47]:
images = torch.rand(32, 3, 224, 224)

print("Batch shape:", images.shape)
print("Number of images:", images.shape[0])
print("Channels:", images.shape[1])
print("Height:", images.shape[2])
print("Width:", images.shape[3])

Batch shape: torch.Size([32, 3, 224, 224])
Number of images: 32
Channels: 3
Height: 224
Width: 224


# 24. Parameter Cheat Sheet

| Function | Important Parameters | What They Control |
|---|---|---|
| `torch.tensor()` | `data`, `dtype`, `device`, `requires_grad` | Tensor contents and configuration |
| `torch.zeros()` | `size`, `dtype`, `device` | Shape and configuration |
| `torch.ones()` | `size`, `dtype`, `device` | Shape and configuration |
| `torch.full()` | `size`, `fill_value` | Shape and stored value |
| `torch.empty()` | `size`, `dtype`, `device` | Uninitialized tensor |
| `torch.arange()` | `start`, `end`, `step` | Numeric sequence |
| `torch.linspace()` | `start`, `end`, `steps` | Number of evenly spaced points |
| `torch.rand()` | `size` | Uniform random tensor |
| `torch.randn()` | `size` | Normal random tensor |
| `torch.randint()` | `low`, `high`, `size` | Random integers |
| `.reshape()` | `shape` | New tensor shape |
| `.flatten()` | `start_dim`, `end_dim` | Dimensions to flatten |
| `.unsqueeze()` | `dim` | Where to add dimension |
| `.squeeze()` | `dim` | Which size-1 dimension to remove |
| `.to()` | `device`, `dtype` | Device/type conversion |

# 25. Mini Exercises

## Exercise 1 — Tensor Creation

Create a tensor containing:

```text
5, 10, 15, 20, 25
```

Then print:

- tensor
- shape
- number of dimensions
- number of elements
- dtype
- device

---

## Exercise 2 — Matrix

Create a `3 × 4` tensor containing only `5`.

Then change it to a `4 × 2` tensor containing `100`.

---

## Exercise 3 — Random Tensor

Create a `5 × 5` random tensor using:

- `rand()`
- `randn()`
- `randint()`

Compare their outputs.

---

## Exercise 4 — Reshape

Create numbers from `1` to `24`.

Reshape them into:

```text
(4, 6)
(2, 3, 4)
(6, 4)
```

Explain why all three are valid.

---

## Exercise 5 — Image Tensor

Create a batch of:

```text
16 RGB images
224 × 224
```

Print its:

- shape
- dimensions
- number of elements
- dtype
- device

# 26. Final Challenge 🚀

Without copying the previous examples, create the following tensor:

```text
Batch size = 8
Channels = 3
Height = 128
Width = 128
```

Requirements:

1. Create it using random values.
2. Make sure it uses `float32`.
3. Automatically select CUDA if available, otherwise CPU.
4. Print the tensor shape.
5. Print the dtype.
6. Print the device.
7. Calculate the total number of elements.
8. Calculate the mean value.
9. Extract the first image.
10. Add a new dimension to that first image and verify its shape.

### Expected conceptual shape flow

```text
Batch
(8, 3, 128, 128)
      ↓
First image
(3, 128, 128)
      ↓
Add batch dimension
(1, 3, 128, 128)
```

If you can complete this without looking back, you understand the core tensor concepts of PyTorch.

In [48]:
# Your solution here

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

images = torch.rand(
    8, 3, 128, 128,
    dtype=torch.float32,
    device=device
)

print("Shape:", images.shape)
print("Dimensions:", images.ndim)
print("Dtype:", images.dtype)
print("Device:", images.device)
print("Number of elements:", images.numel())
print("Mean:", images.mean())

first_image = images[0]
print("\nFirst image shape:", first_image.shape)

first_image_batched = first_image.unsqueeze(0)
print("After unsqueeze:", first_image_batched.shape)

Shape: torch.Size([8, 3, 128, 128])
Dimensions: 4
Dtype: torch.float32
Device: cuda:0
Number of elements: 393216
Mean: tensor(0.5006, device='cuda:0')

First image shape: torch.Size([3, 128, 128])
After unsqueeze: torch.Size([1, 3, 128, 128])


# 27. Key Takeaways

You should now understand:

### PyTorch fundamentals
- What PyTorch is
- Why tensors are important
- CPU vs GPU computation

### Tensor creation
- `tensor`
- `zeros`
- `ones`
- `full`
- `empty`
- `arange`
- `linspace`
- `rand`
- `randn`
- `randint`

### Tensor properties
- `shape`
- `ndim`
- `numel`
- `dtype`
- `device`

### Tensor manipulation
- Indexing
- Slicing
- Reshaping
- Flattening
- Squeezing
- Unsqueezing
- Concatenation
- Stacking

### Tensor mathematics
- Element-wise operations
- Matrix multiplication
- Reductions
- Dimension-based operations

### Hardware
- CUDA detection
- Device selection
- Moving tensors between CPU and GPU

### Reproducibility
- Random seeds

### Next step

The next notebook will go deeper into **tensor operations, broadcasting, matrix mathematics, memory/layout concepts, and more advanced tensor manipulation**.

➡️ **Next: `02_Tensors_and_Operations.ipynb`**