# t-SNE (t-Distributed Stochastic Neighbor Embedding)

# DATA

In [1]:
import numpy as np

X = np.array([
    [1, 2],
    [2, 1],
    [2, 3],
    [8, 8],
    [9, 8],
    [8, 9]
], dtype=float)

print(X)

[[1. 2.]
 [2. 1.]
 [2. 3.]
 [8. 8.]
 [9. 8.]
 [8. 9.]]


# Pairwise Distance Matrix Using Euclidean distance

In [11]:
def dis_matrix(X):

    n = len(X)
    # empty matrix
    distance = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            distance[i][j] = np.sqrt(np.sum((X[i] - X[j]) ** 2))

    print(distance)


dis_matrix(X)

[[ 0.          1.41421356  1.41421356  9.21954446 10.          9.89949494]
 [ 1.41421356  0.          2.          9.21954446  9.89949494 10.        ]
 [ 1.41421356  2.          0.          7.81024968  8.60232527  8.48528137]
 [ 9.21954446  9.21954446  7.81024968  0.          1.          1.        ]
 [10.          9.89949494  8.60232527  1.          0.          1.41421356]
 [ 9.89949494 10.          8.48528137  1.          1.41421356  0.        ]]


SyntaxError: invalid syntax (1455399123.py, line 1)