# Elastic net Regression

In [115]:
import numpy as np

# Dataset

In [116]:
X = [
    [2, 80, 70, 15, 200],
    [3, 85, 72, 18, 180],
    [5, 90, 78, 14, 210],
    [6, 92, 85, 20, 190],
    [8, 95, 88, 16, 220],
    [9, 96, 91, 21, 230],
    [11, 98, 94, 19, 240],
    [12, 99, 96, 17, 250],
    [14, 100, 98, 22, 260],
    [15, 100, 99, 18, 270]
]

X = np.array(X)

y = [
    65,
    68,
    75,
    80,
    86,
    90,
    95,
    97,
    99,
    100
]

y = np.array(y)

# Normalization

In [117]:
X = (X - X.mean(axis=0)) / X.std(axis=0)
X

array([[-1.52153491, -2.10194715, -1.700756  , -1.22474487, -0.87038828],
       [-1.28745262, -1.32344821, -1.50183717,  0.        , -1.5666989 ],
       [-0.81928803, -0.54494926, -0.90508068, -1.63299316, -0.52223297],
       [-0.58520574, -0.23354968, -0.20886477,  0.81649658, -1.21854359],
       [-0.11704115,  0.23354968,  0.08951347, -0.81649658, -0.17407766],
       [ 0.11704115,  0.38924947,  0.38789172,  1.22474487,  0.17407766],
       [ 0.58520574,  0.70064905,  0.68626997,  0.40824829,  0.52223297],
       [ 0.81928803,  0.85634884,  0.8851888 , -0.40824829,  0.87038828],
       [ 1.28745262,  1.01204863,  1.08410763,  1.63299316,  1.21854359],
       [ 1.52153491,  1.01204863,  1.18356704,  0.        ,  1.5666989 ]])

# Parameters

In [118]:
W = np.full(X.shape[1], 0.5)
b = 0.5
l1 = 0.01
l2 = 0.01
lr = 0.001

# Prediction

In [119]:
def predict(X, W, b):
    return np.dot(X, W) + b

predict(X, W, b)

array([-3.20968561, -2.33971845, -1.71227205, -0.2148336 ,  0.10772389,
        1.64650243,  1.951303  ,  2.01148283,  3.61757281,  3.14192474])

# Loss

In [ ]:
def elastic_MSE(X, y, W, b, l1, l2):
    mse_loss = np.mean((y-predict(X, W, b))**2)
    ridge_loss = l2 * np.sum(W**2)
    lasso_loss = l1 * np.sum(np.abs(W))
    
    elastic_loss = mse_loss + ridge_loss + lasso_loss

    # print(ridge_loss)
    # print(lasso_loss)
    # print(mse_loss)
    
    return elastic_loss

elastic_MSE(X, y, W, b, l1, l2)

np.float64(7326.38006088827)

# Gradient descent

In [121]:
def gradient_descent(X, y, W, b, l1, l2, lr):
    
    n = X.shape[0]

    dW = ((-2/n) * np.dot(X.T, (y - predict(X, W, b)))) + (2 * l2 * W) + (l1 * np.sign(W))
    db = (-2/n) * np.sum(y - predict(X, W, b))

    W = W - (dW * lr)
    b = b - (db * lr)

    return W, b

In [122]:
epochs = 10000
for epoch in range(epochs):
    loss = elastic_MSE(X, y, W, b, l1, l2)
    W, b = gradient_descent(X, y, W, b, l1, l2, lr)
    if epoch % 1000 == 0:
        print("predict : ", predict(X, W, b))
        print("Loss : ", loss)
        print("W : ", W)
        print("b : ", b)

predict :  [-3.17327067 -2.28006775 -1.61308464 -0.07950278  0.27049217  1.8495978
  2.17403565  2.24418627  3.8932255   3.41438847]
Loss :  7326.38006088827
W :  [0.51970057 0.51968872 0.52000211 0.50992635 0.5184393 ]
b :  0.67
predict :  [53.99943294 57.09058898 64.08809625 68.43071376 73.48349419 78.5049713
 81.95480426 83.91695981 89.29625567 89.65944846]
Loss :  133.44264796391903
W :  [2.87424241 3.21052238 3.16702555 0.96031583 2.71023352]
b :  74.04247656084777
predict :  [63.71843361 66.79692254 74.31236907 78.2918959  83.73177015 88.20327461
 91.90304823 94.0809562  98.86945367 99.61682671]
Loss :  3.8285646389722294
W :  [2.78178235 3.44590485 3.35989296 0.68565539 2.53250374]
b :  83.95249506826923
predict :  [ 64.87575861  68.07144395  75.7639232   79.72964916  85.25011388
  89.49218728  93.27450099  95.51667229 100.03810342 100.89751707]
Loss :  1.3687902242321979
W :  [2.68671556 3.60742331 3.51454724 0.57750125 2.36676522]
b :  85.29098698541199
predict :  [ 64.9155275

In [ ]:
y

array([ 65,  68,  75,  80,  86,  90,  95,  97,  99, 100])

: 