# Ridge Regression

In [79]:
import numpy as np
import pandas as pd

# Data

Feature	Meaning

x1	Study Hours

x2	Attendance

x3	Previous Score

x4	Random Noise

x5	Random Noise

y	Final Score

In [80]:
X = [
    [2, 80, 70, 15, 200],
    [3, 85, 72, 18, 180],
    [5, 90, 78, 14, 210],
    [6, 92, 85, 20, 190],
    [8, 95, 88, 16, 220],
    [9, 96, 91, 21, 230],
    [11, 98, 94, 19, 240],
    [12, 99, 96, 17, 250],
    [14, 100, 98, 22, 260],
    [15, 100, 99, 18, 270]
]

X = np.array(X)

y = [
    65,
    68,
    75,
    80,
    86,
    90,
    95,
    97,
    99,
    100
]

y = np.array(y)

# Normalization

In [81]:
X = (X - X.mean(axis=0)) / X.std(axis=0)
X

array([[-1.52153491, -2.10194715, -1.700756  , -1.22474487, -0.87038828],
       [-1.28745262, -1.32344821, -1.50183717,  0.        , -1.5666989 ],
       [-0.81928803, -0.54494926, -0.90508068, -1.63299316, -0.52223297],
       [-0.58520574, -0.23354968, -0.20886477,  0.81649658, -1.21854359],
       [-0.11704115,  0.23354968,  0.08951347, -0.81649658, -0.17407766],
       [ 0.11704115,  0.38924947,  0.38789172,  1.22474487,  0.17407766],
       [ 0.58520574,  0.70064905,  0.68626997,  0.40824829,  0.52223297],
       [ 0.81928803,  0.85634884,  0.8851888 , -0.40824829,  0.87038828],
       [ 1.28745262,  1.01204863,  1.08410763,  1.63299316,  1.21854359],
       [ 1.52153491,  1.01204863,  1.18356704,  0.        ,  1.5666989 ]])

# W (Weight) and b (bais)

In [82]:
W = np.full(X.shape[1], 0.5)
b = 0.5
lam = 0.1

# Predict

In [83]:
def predict(x, W, b):
    return np.dot(x, W) + b

predict(X, W, b)

array([-3.20968561, -2.33971845, -1.71227205, -0.2148336 ,  0.10772389,
        1.64650243,  1.951303  ,  2.01148283,  3.61757281,  3.14192474])

# Loss

In [84]:
def lasso_MSE(x, y, W, b, lam):

    # Lam controll the loss

    n = x.shape[0]
    MSE_loss = np.mean((y - predict(x, W, b))**2)
    lasso_loss = MSE_loss + (lam * np.sum(np.abs(W)))
    return lasso_loss

lasso_MSE(X, y, W, b, lam)

np.float64(7326.592560888271)

# Learning or gradient Descent

In [85]:
def gradient_descent(X, y, W, b, lam):
    n = X.shape[0]

    dw = (-2/n * np.dot(X.T, (y - predict(X, W, b)))) + (lam * np.sign(W))
    db = (-2/n * np.sum(y - predict(X, W, b)))

    # print(dw)
    # print(db)
    lr = 0.001
    W = W - (lr * dw)
    b = b - (lr * db)

    return W, b

# gradient_descent(X, y, W, b, 2)


# Iterate for 50 epocs

In [86]:
epochs = 10000
for epoch in range(epochs):
    loss = lasso_MSE(X, y, W, b, lam)
    W, b = gradient_descent(X, y, W, b, lam)
    if epoch % 1000 == 0:
        print("predict : ", predict(X, W, b))
        print("Loss : ", loss)
        print("W : ", W)
        print("b : ", b)

predict :  [-3.17267712 -2.2796134  -1.61273067 -0.07938841  0.27055493  1.84941436
  2.17380344  2.24394443  3.89272668  3.41396576]
Loss :  7326.592560888271
W :  [0.51962057 0.51960872 0.51992211 0.50984635 0.5183593 ]
b :  0.67
predict :  [54.03110224 57.09822403 64.13228219 68.4195012  73.50730773 78.47307374
 81.94249885 83.92377591 89.24690386 89.65009586]
Loss :  134.22097133384295
W :  [2.87370093 3.21223922 3.17034404 0.93401436 2.70117377]
b :  74.04247656084777
predict :  [63.74100549 66.79625233 74.36978723 78.28012424 83.77098723 88.16059501
 91.89229841 94.09925075 98.80451205 99.61013793]
Loss :  4.587002205882038
W :  [2.78182796 3.45569662 3.37346797 0.64636165 2.51160958]
b :  83.95249506826923
predict :  [ 64.88596053  68.06713704  75.82803511  79.72568641  85.30143384
  89.44485436  93.26578596  95.5416256   99.96152605 100.88782495]
Loss :  2.1136381376289344
W :  [2.68518108 3.62534326 3.53987025 0.53031714 2.33136294]
b :  85.29098698541199
predict :  [ 64.91310

In [87]:
y

array([ 65,  68,  75,  80,  86,  90,  95,  97,  99, 100])