
# Multiple Linear Regression




In [6]:
# Libraries
import numpy as np

# input

In [7]:
# 2 features
X = np.array([[1, 2],
              [2, 3],
              [4, 5],
              [6, 7]])

y = np.array([5, 8, 14, 20])

In [8]:
X.T

array([[1, 2, 4, 6],
       [2, 3, 5, 7]])

# weight w_1, w_2 and bais b

In [9]:
num_features = X.shape[1] # shape -> row, columns here we are getting columns
# W = np.zeros(num_features) # [0, 0] because for two features w_1 and w_2
W = np.array([0.5, 0.5])

b = 0.5 # bais


##  Predict in Multiple Linear Regression

###  We use the dot product here:
```python
np.dot(X, W)
```
## Example
```python
X = [[1, 2],
     [2, 3],
     [4, 5]]
W = [0.5, 0.7]
```

```python
[1*0.5 + 2*0.7,    # → 0.5 + 1.4 = 1.9
 2*0.5 + 3*0.7,    # → 1.0 + 2.1 = 3.1
 4*0.5 + 5*0.7]    # → 2.0 + 3.5 = 5.5
 ```

In [ ]:
print(X)
print(W)
print(X.shape)
print(W.shape)
def predict(X, y, W, b):
  return np.dot(X, W) + b

[[1 2]
 [2 3]
 [4 5]
 [6 7]]
[1.37157423 1.56547422]
(4, 2)
(2,)


: 

In [11]:
y_pred = predict(X, y, W, b)
print(y_pred)

[2. 3. 5. 7.]



## 📌 Compute Gradients for Linear Regression

---

### 🎯 Loss Function (MSE)

$$[
L = \frac{1}{n} \sum_{i=1}^{n} (y_i - (w_1 x_i + b))^2
]$$

Let:
$$[
u_i = y_i - (w_1 x_i + b)
\quad \Rightarrow \quad L = \frac{1}{n} \sum u_i^2
]$$

---

## 🔹 Derivative w.r.t \( b \) (Bias)

### 🧠 **Quick Matrix Style** (for notes/code):
$$[
\frac{\partial L}{\partial b} = -\frac{2}{n} \sum_{i=1}^{n} (y_i - (w_1 x_i + b))
]$$

### 📘 **Detailed Chain Rule**:
1. $$( u_i = y_i - (w_1 x_i + b) )$$
2. $$( L = u_i^2 )$$
3. Apply chain rule:

$$[
\frac{\partial L}{\partial b} = \frac{\partial L}{\partial u_i} \cdot \frac{\partial u_i}{\partial b}
= 2u_i \cdot (-1)
]$$

$$[
\Rightarrow \frac{\partial L}{\partial b} = -\frac{2}{n} \sum u_i = -\frac{2}{n} \sum (y_i - (w_1 x_i + b))
]$$

---

## 🔹 Derivative w.r.t \( w_1 \) (Weight)

### 🧠 **Quick Matrix Style** (for notes/code):
$$[
\frac{\partial L}{\partial w_1} = -\frac{2}{n} \sum_{i=1}^{n} x_i (y_i - (w_1 x_i + b))
]$$

### 📘 **Detailed Chain Rule**:
1. $$( u_i = y_i - (w_1 x_i + b))$$
2. $$( L = u_i^2)$$
3. Apply chain rule:

$$[
\frac{\partial L}{\partial w_1} = \frac{\partial L}{\partial u_i} \cdot \frac{\partial u_i}{\partial w_1}
= 2u_i \cdot (-x_i)
]$$

$$[
\Rightarrow \frac{\partial L}{\partial w_1} = -\frac{2}{n} \sum x_i (y_i - (w_1 x_i + b))
]$$

---

### ✅ Code Summary

```python
dw = (-2 / n) * np.dot(x.T * (y - y_pred)) # why dot cause in y_pred we did x * w using dot same here. y as single row but x has 2columns so transposed and used dot
db = (-2 / n) * np.sum(y - y_pred)


In [12]:
# Gradient descent
def compute_grad(X, y, W, b):

  #predict
  y_pred = predict(X, y, W, b)

  n = X.shape[0]

  #derivatie of MSE WRT weight(W)
  dW = (-2/n) * np.dot(X.T, (y -  y_pred))
  # print("dW : ", dW)

  #derivatie of MSE WRT bais(b)
  db = (-2/n) * np.sum(y -  y_pred)
  # print("db: ", db)

  # learning rate
  alpha = 0.001

  #update parameters
  W = W - (alpha * dW)
  b = b - (alpha * db)

  return W, b

In [13]:
for epochs in range(0, 100):
  if(epochs % 10 == 0):
      print("Epochs", epochs)
      print("Weight : ", W)
      print("bais : ", b)
      print("predict: ", predict(X, y, W, b))
  W, b = compute_grad(X, y, W, b)

Epochs 0
Weight :  [0.5 0.5]
bais :  0.5
predict:  [2. 3. 5. 7.]
Epochs 10
Weight :  [0.96170398 1.07037942]
bais :  0.6086754433336797
predict:  [ 3.71113826  5.74322166  9.80738845 13.87155524]
Epochs 20
Weight :  [1.17756208 1.33629111]
bais :  0.6587290283379426
predict:  [ 4.50887334  7.02272653 12.05043293 17.07813932]
Epochs 30
Weight :  [1.2787081 1.4601422]
bais :  0.6814341028292005
predict:  [ 4.8804266   7.6192769  13.09697749 18.57467809]
Epochs 40
Weight :  [1.32632789 1.5177104 ]
bais :  0.6913825099092297
predict:  [ 5.05313119  7.89716948 13.58524605 19.27332262]
Epochs 50
Weight :  [1.34897026 1.54435291]
bais :  0.6953826506728701
predict:  [ 5.13305872  8.02638189 13.81302822 19.59967455]
Epochs 60
Weight :  [1.35995584 1.55656708]
bais :  0.6966112413482661
predict:  [ 5.16970124  8.08622415 13.91926998 19.75231581]
Epochs 70
Weight :  [1.36549993 1.56205042]
bais :  0.6965504863550651
predict:  [ 5.18615126  8.11370161 13.96880231 19.82390301]
Epochs 80
Weight :  