In [1]:
l = [1, 2, 3]

print(l * 2)

[1, 2, 3, 1, 2, 3]


In [3]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr * 2)

[2 4 6]


In [6]:
# Boolean masking

# [1, 2, 3, 4]
#  F  F  T  F

arr = np.arange(1, 10)

arr_mask = arr > 5

arr_mask

array([False, False, False, False, False,  True,  True,  True,  True])

In [8]:
arr1 = arr[arr_mask]

In [10]:
np.where(arr > 5)

(array([5, 6, 7, 8]),)

In [18]:
# 1 Dem

x = [1 , 2, 3]

# 2d 
y = [[1, 2, 3],
    [4, 5, 6]]

# 3d 
z = [[[1, 2, 3],
    [4, 5, 6]],
    
    [[1, 2, 3],
     [1, 2, 3]]
    ]

In [17]:
# np.reshape(y, (6, 1))

In [25]:
y = np.array(y)

a = y.view()
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(type(a))

print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
x = np.zeros((3, 5, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

: 

In [33]:
x[1, 1, 1] = 2
x

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 2.]],

       [[0., 0.],
        [0., 0.]]])