# Random Forest

In [715]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [716]:
data = load_iris()

X = data.data
y = data.target

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [717]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [718]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [719]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3, train_size = 0.7, random_state = 42, shuffle = True)


print(train_X.shape)
print(test_X.shape)
print(train_y.shape)
print(test_y.shape)

(105, 4)
(45, 4)
(105,)
(45,)


# Bootstrap

In [720]:
def bootstrap_sample(X, y):
    # print(X.shape[0])
    indices = np.random.choice(a = X.shape[0], size = X.shape[0], replace = True)
    
    # print(indices)

    X_sample = X[indices]
    y_sample = y[indices]

    return X_sample, y_sample

bootstrap_sample(train_X, train_y)

(array([[5.1, 3.5, 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [4.4, 3. , 1.3, 0.2],
        [6.1, 3. , 4.6, 1.4],
        [5.1, 3.8, 1.9, 0.4],
        [6.7, 3.3, 5.7, 2.1],
        [6.1, 2.6, 5.6, 1.4],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [5.1, 2.5, 3. , 1.1],
        [6.1, 3. , 4.6, 1.4],
        [6.7, 3.1, 5.6, 2.4],
        [6.7, 3. , 5. , 1.7],
        [7.4, 2.8, 6.1, 1.9],
        [6. , 3. , 4.8, 1.8],
        [4.9, 3. , 1.4, 0.2],
        [5.1, 3.8, 1.6, 0.2],
        [4.3, 3. , 1.1, 0.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.7, 3.3, 5.7, 2.5],
        [5.3, 3.7, 1.5, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [5.4, 3.9, 1.7, 0.4],
        [6.7, 3.1, 5.6, 2.4],
        [4.9, 3. , 1.4, 0.2],
        [5.4, 3.4, 1.7, 0.2],
        [6.7, 3. , 5. , 1.7],
        [6.7, 3.3, 5.7, 2.1],
        [6.9, 3.1, 4.9, 1.5],
        [6.7, 3.1, 5.6, 2.4],
        [4.8, 3.4, 1.9, 0.2],
        [5.7, 2.9, 4.2, 1.3],
        [4

# Decision Tree

In [721]:
class DecisionTree():
        
    def gini(self, x):
        values, counts = np.unique(x, return_counts = True)
        probs = counts / np.sum(counts)
        return 1 - np.sum(probs ** 2)

    def split(self, X, y, threshold, feature):
        # print(X[:, feature].shape)
        # print(threshold)

        left_mask = X[:, feature] <= threshold
        right_mask = X[:, feature] > threshold

        return X[left_mask], X[right_mask], y[left_mask], y[right_mask]

    def get_threshold(self, thresholds, y):

        index = np.argsort(thresholds)

        thresholds = thresholds[index]
        y = y[index]

        new_thresholds = []

        for i in range(len(thresholds)-1):

            if y[i] != y[i+1]:
                new_thresholds.append((thresholds[i] + thresholds[i+1])/2)

        return np.array(new_thresholds)

    def best_split(self, X, y, n_features):

        best_gini = float("inf")
        best_threshold = None
        best_feature = None

        indices = np.random.choice(X.shape[1], size = n_features, replace = False)

        for feature in indices:
            thresholds = X[:, feature]

            thresholds = self.get_threshold(thresholds, y)

            if len(thresholds) == 0:
                continue

            for threshold in thresholds:

                LX, RX, Ly, Ry = self.split(X, y, threshold, feature)

                if len(Ly) == 0 or len(Ry) == 0:
                    continue

                gini_l = self.gini(Ly)
                gini_r = self.gini(Ry)

                weighted_gini = len(Ly)/X.shape[0] * gini_l + len(Ry)/X.shape[0] * gini_r

                if best_gini > weighted_gini:
                    best_gini = weighted_gini
                    best_threshold = threshold
                    best_feature = feature

        return best_gini, best_threshold, best_feature

    def fit(self, X, y, depth = 0, max_depth = 10, n_features = 2, min_samples_split = 2):
        
        if len(np.unique(y)) == 1:
            return {"label" : y[0]}
        
        if depth >= max_depth or len(y) < min_samples_split:
            values, counts = np.unique(y, return_counts = True)
            return {"label" : values[np.argmax(counts)]}

        best_gini, best_threshold, best_feature = self.best_split(X, y, n_features)

        if best_feature is None:
            values, counts = np.unique(y, return_counts = True)
            return {"label" : values[np.argmax(counts)]}

        XL, XR, yL, yR = self.split(X, y, best_threshold, best_feature)

        return {"feature" : best_feature,
                "threshold" : best_threshold,
                "left" : self.fit(XL, yL, depth+1, max_depth, n_features, min_samples_split),
                "right" : self.fit(XR, yR, depth+1, max_depth, n_features, min_samples_split)
                }

    def predict(self, x, tree):
        if "label" in tree:
            return tree["label"]
    
        if x[tree["feature"]] <= tree["threshold"]:
            return self.predict(x, tree["left"])
        else:
            return self.predict(x, tree["right"])



# Build the model from scratch Random Forest

In [722]:
class RandomForest():

    def __init__(self, min_samples_split, n_features, n_trees = 10, max_depth = 3):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.n_features = n_features
        self.trees = []

    def fit(self, X, y):
        
        self.trees = []

        for tree in range(self.n_trees):

            sample_X, sample_y = bootstrap_sample(X, y)            

            # print(sample_X.shape)
            # print(sample_y.shape)
            
            decisiontree = DecisionTree()

            tree = decisiontree.fit(sample_X, sample_y, max_depth = self.max_depth, n_features = self.n_features, min_samples_split = self.min_samples_split)

            self.trees.append(tree)

            # print(tree)

    def predict(self, X):
        
        predictions = []

        decisiontree = DecisionTree()

        for tree in self.trees:
            prediction = []
            for x in X:
                prediction.append(decisiontree.predict(x, tree))
            predictions.append(prediction)

        predictions = np.array(predictions).T

        final_pred = []
        
        for row in predictions:
            values, counts = np.unique(row, return_counts = True)

            final_pred.append(values[np.argmax(counts)])
            
        return np.array(final_pred)


In [723]:
forest = RandomForest(
    n_trees=5,
    max_depth=10,
    min_samples_split=2,
    n_features=2
)

print(forest.n_trees)
print(forest.max_depth)
print(forest.min_samples_split)
print(forest.n_features)
print(forest.trees)

5
10
2
2
[]


In [724]:
forest.fit(X, y)
print(len(forest.trees))

5


In [725]:
forest.predict(test_X)
# forest.predict(test_X[0])

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])